apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: ghost
  version: v3.6.0

resources:
- deployments.yaml
- services.yaml
#- ingress.yaml
- traefik-ingressroute.yaml
