apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: traefik
  version: 2.1.3

resources:
- crds.yaml
- rbac.yaml
- dashboard-hook-ingressroute.yaml
- deployments.yaml
- services.yaml
